### ISSUE TITLE
Borken Pipe with Scanner on Mac OS

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Scanner_Python#9] opened 2019-10-27 17:50 UTC
This is happening after few hours of run but hard rot reproduce. 

specifications 

Mac OS Mojave - Mac mini 2018

''''
Traceback (most recent call last):
  File "./run.py", line 72, in <module>
    cityscopy.scan()
  File "/Users/cityscience/Documents/GitHub/CS_CityScoPy/cityscopy.py", line 60, in scan
    self.scanner_function(self.multiprocess_shared_dict)
  File "/Users/cityscience/Documents/GitHub/CS_CityScoPy/cityscopy.py", line 172, in scanner_function
    THIS_FRAME, KEY_STONE_DATA, (video_resolution_x, video_resolution_y))
cv2.error: OpenCV(4.1.0) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/imgwarp.cpp:2903: error: (-215:Assertion failed) _src.total() > 0 in function 'warpPerspective'

Process Process-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cityscience/Documents/GitHub/CS_CityScoPy/cityscopy.py", line 323, in create_data_json
    scan_results = multiprocess_shared_dict['scan']
  File "<string>", line 2, in __getitem__
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/managers.py", line 818, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
''''

**Comment by RELNO** [comment] 2019-10-27 20:15
The problem is in  `-215:Assertion failed` (`brokenPipeError` is only a multiprocessing failure afterwards).   Assertion failed happens when image data is not funneld as needed to whatever CV method (in this case, warpPerspective). 

As you've noted yourself, reproducing is hard since it is not clear why a webcam suddenly has a 'jump' in data transfer. To eliminate external causes, I'd suggest to run the tool while not running other demanding processes -- My main concern is that whatever else is running might choke GPU/CPU for a split second thus breaking the webcam data stream.

**Comment by agrignard** [comment] 2019-10-28 14:14
Maybe this can help 
https://stackoverflow.com/questions/26692284/how-to-prevent-brokenpipeerror-when-doing-a-flush-in-python

Like having a try/catch in the code?

**Comment by agrignard** [comment] 2019-10-29 20:38
Is there a way to clean the python cache or something like this?

the problem is that ones this happens ones then I need to restart the computer to retake it work. If I rerun it there is no way to get back the original camera

Note: it seems to happen more easily if there is a new screen plug while scanning

**Comment by RELNO** [comment] 2019-10-29 20:56
added try-catch, test and open if still crashing.

**Comment by agrignard** [comment] 2019-10-29 21:21
same problem (now easy to reproduce)

''''
Traceback (most recent call last):
  File "./run.py", line 72, in <module>
    cityscopy.scan()
  File "/Users/cityscience/Documents/GitHub/CS_CityScoPy/cityscopy.py", line 60, in scan
    self.scanner_function(self.multiprocess_shared_dict)
  File "/Users/cityscience/Documents/GitHub/CS_CityScoPy/cityscopy.py", line 172, in scanner_function
    THIS_FRAME, KEY_STONE_DATA, (video_resolution_x, video_resolution_y))
cv2.error: OpenCV(4.1.0) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/imgwarp.cpp:2903: error: (-215:Assertion failed) _src.total() > 0 in function 'warpPerspective'

Process Process-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cityscience/Documents/GitHub/CS_CityScoPy/cityscopy.py", line 323, in create_data_json
    scan_results = multiprocess_shared_dict['scan']
  File "<string>", line 2, in __getitem__
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/managers.py", line 818, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
'''''

**Comment by RELNO** [comment] 2019-10-29 21:44
Tried another method using [`retval` checks](https://stackoverflow.com/questions/35242735/can-not-read-or-play-a-video-in-opencvpython-using-videocapture).

**Comment by agrignard** [comment] 2019-10-30 13:47
same issue

pretty easy to reproduce on on Mac OS just plug and unplug an external screen

**Comment by RELNO** [comment] 2019-10-30 15:29
seemed to be resolved by https://github.com/CityScope/CS_CityScoPy/commit/27de9d436be1f99eeee28de18f214a01bf7297be

**Closed as completed by RELNO** 2019-10-30 15:29 UTC

**Comment by agrignard** [comment] 2019-10-30 15:36
ok fixed! thanks
